name: Deploy 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 192.168.65.134 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          # Replace these placeholders with your deployment commands
          ssh git@192.168.65.135 'cd /var/www/devops && git pull origin main'
          # Additional deployment commands as needed

